server.port=9009

#spring.application.name=shop
#spring.datasource.url=jdbc:postgresql://localhost:5432/shopdb?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=Asia/Dhaka
#spring.datasource.username=shop
#spring.datasource.password=shop12345
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show_sql=false
spring.jpa.properties.hibernate.format_sql=false

# Hikari Configuration
spring.datasource.hikari.minimumIdle=1
spring.datasource.hikari.maximumPoolSize=15
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.poolName=SpringBootJPAHikariCP
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000


#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:bank.sql, classpath:db_script.sql, classpath:org.sql

#File upload size Limit
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

jwt.signing.key.secret=mySecretKeyForJWTTokenGenerationThatIsAtLeast512BitsLongAndVerySecure1234567890!@#$%^&*()
jwt.token.expiration.in.seconds=86400000
upload-dir=/uploads

spring.liquibase.change-log=classpath:db/changelog/master.yaml
spring.liquibase.enabled=true

# To auto-run SQL scripts
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true

# If using BCrypt password encoding in your app
spring.security.password.encoder.bcrypt.strength=10
spring.devtools.restart.enabled=false